project:
  type: book
  output-dir: docs

lang: uk-UA

title-block-banner: true

book:
  title: "Завдання з курсу"
  author: "Олександр Виноградов"
  date: "1/20/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - darkly
      - brand

crossref: 
  tbl-title: "Таблиця"
  tbl-prefix: "Таб."
  
toc-title: "Зміст"
author-title: "автор"
published-title: "опубліковано"