project:
  type: book
  output-dir: docs

lang: uk-UA

book:
  title: "Завдання з курсу"
  author: "Олександр Виноградов"
  date: "1/20/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - United

title-block-banner: true
title-block-banner-color: "#ffff00"
monobackgroundcolor: "#ffffcc"

crossref: 
  tbl-title: "Таблиця"
  tbl-prefix: "Таб."
  
toc-title: "на цій сторінці"
author-title: "автор"
published-title: "опубліковано"
